/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.limitd.Request', null, global);
goog.exportSymbol('proto.limitd.Request.Method', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.limitd.Request = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.limitd.Request, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.limitd.Request.displayName = 'proto.limitd.Request';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.limitd.Request.prototype.toObject = function(opt_includeInstance) {
  return proto.limitd.Request.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.limitd.Request} msg The msg instance to transform.
 * @return {!Object}
 */
proto.limitd.Request.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    type: jspb.Message.getField(msg, 2),
    key: jspb.Message.getField(msg, 3),
    method: jspb.Message.getField(msg, 4),
    count: jspb.Message.getFieldWithDefault(msg, 5, 1),
    all: jspb.Message.getFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.limitd.Request}
 */
proto.limitd.Request.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.limitd.Request;
  return proto.limitd.Request.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.limitd.Request} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.limitd.Request}
 */
proto.limitd.Request.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = /** @type {!proto.limitd.Request.Method} */ (reader.readEnum());
      msg.setMethod(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.limitd.Request.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.limitd.Request.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.limitd.Request} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.limitd.Request.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {!proto.limitd.Request.Method} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.limitd.Request.Method = {
  TAKE: 0,
  WAIT: 1,
  PUT: 2,
  STATUS: 3,
  PING: 4
};

/**
 * required string id = 1;
 * @return {string}
 */
proto.limitd.Request.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.limitd.Request.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.limitd.Request.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required string type = 2;
 * @return {string}
 */
proto.limitd.Request.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.limitd.Request.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.limitd.Request.prototype.clearType = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required string key = 3;
 * @return {string}
 */
proto.limitd.Request.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.limitd.Request.prototype.setKey = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.limitd.Request.prototype.clearKey = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasKey = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required Method method = 4;
 * @return {!proto.limitd.Request.Method}
 */
proto.limitd.Request.prototype.getMethod = function() {
  return /** @type {!proto.limitd.Request.Method} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.limitd.Request.Method} value */
proto.limitd.Request.prototype.setMethod = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.limitd.Request.prototype.clearMethod = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasMethod = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 count = 5;
 * @return {number}
 */
proto.limitd.Request.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 1));
};


/** @param {number} value */
proto.limitd.Request.prototype.setCount = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.limitd.Request.prototype.clearCount = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasCount = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool all = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.limitd.Request.prototype.getAll = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.limitd.Request.prototype.setAll = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.limitd.Request.prototype.clearAll = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.limitd.Request.prototype.hasAll = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.limitd);
